install.packages('bit64', repos='http://cran.us.r-project.org')
install.packages('plyr', repos='http://cran.us.r-project.org')
install.packages('ggplot2', repos='http://cran.us.r-project.org')
install.packages('data.table', repos='http://cran.us.r-project.org')
install.packages('knitr', repos='http://cran.us.r-project.org')
install.packages('reshape2', repos='http://cran.us.r-project.org')
install.packages('scales', repos='http://cran.us.r-project.org')
install.packages('bigrf', repos='http://cran.us.r-project.org')